version: 2
jobs:
  node:
    working_directory: ~/demo-react-native
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            npm run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml